Repository lalalilo/express-sequelize-crud, pull requests merged in 2020-03, with the labels that each got.

#14 ✨ add sautocomplete support
  README.md
  package.json
  src/index.ts
  tests/index.spec.ts
  tsconfig.json
  yarn.lock
Labels: size/L

#15 ♻️ split in multiple files
  .circleci/config.yml
  .nvmrc
  package.json
  src/create.ts
  src/delete.ts
  src/getList.spec.ts
  src/getList.ts
  src/getOne.ts
  src/headers.spec.ts
  src/headers.ts
  src/index.ts
  src/search.spec.ts
  src/search.ts
  src/update.ts
  tests/index.spec.ts
  tsconfig.json
  yarn.lock
Labels: size/XL

#16 Split multiple files
  README.md
  package.json
  src/index.ts
Labels: size/M

#17 ⬆️Upgrade express dependencies
  package.json
  yarn.lock
Labels: size/M

#21 fix: upgrade express dependencies
  package.json
  yarn.lock
Labels: size/XS
